//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _Layout_cshtml_Execute_About {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Data.
        /// </summary>
        public static string _Layout_cshtml_Execute_ActivityData {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_ActivityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string _Layout_cshtml_Execute_Admin {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Aber.
        /// </summary>
        public static string _Layout_cshtml_Execute_Application_name {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Application_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string _Layout_cshtml_Execute_Challenges {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Challenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string _Layout_cshtml_Execute_Contact {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FitBit.
        /// </summary>
        public static string _Layout_cshtml_Execute_FitBit {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_FitBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _Layout_cshtml_Execute_Home {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string _Layout_cshtml_Execute_Jobs {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Boards.
        /// </summary>
        public static string _Layout_cshtml_Execute_LeaderBoards {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_LeaderBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Auth Tokens.
        /// </summary>
        public static string _Layout_cshtml_Execute_WebServiceAuth {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_WebServiceAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Log_in {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Register {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string account_Code {
            get {
                return ResourceManager.GetString("account_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string account_ConfirmPassword {
            get {
                return ResourceManager.GetString("account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoB.
        /// </summary>
        public static string account_DoB {
            get {
                return ResourceManager.GetString("account_DoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string account_Email {
            get {
                return ResourceManager.GetString("account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string account_Nickname {
            get {
                return ResourceManager.GetString("account_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string account_password {
            get {
                return ResourceManager.GetString("account_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string account_RemeberMe {
            get {
                return ResourceManager.GetString("account_RemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string account_RememberBroswer {
            get {
                return ResourceManager.GetString("account_RememberBroswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string account_Team {
            get {
                return ResourceManager.GetString("account_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string AccountController_Login_Invalid_login_attempt {
            get {
                return ResourceManager.GetString("AccountController_Login_Invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string AccountController_VerifyCode_Invalid_code {
            get {
                return ResourceManager.GetString("AccountController_VerifyCode_Invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Data.
        /// </summary>
        public static string ActivityData {
            get {
                return ResourceManager.GetString("ActivityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Total number of {0}: &lt;span class=&quot;statistic&quot; id=&quot;{0}-total&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///                    &lt;li&gt;Your best day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;
        ///                    &lt;li&gt;Your worst day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;.
        /// </summary>
        public static string AD_AllTimeSummaryStatistics {
            get {
                return ResourceManager.GetString("AD_AllTimeSummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AD_Category {
            get {
                return ResourceManager.GetString("AD_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Create_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Create_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AD_Create_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("AD_Create_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AD_Date {
            get {
                return ResourceManager.GetString("AD_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Delete_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Delete_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AD_Delete_cshtml_Execute_Delete {
            get {
                return ResourceManager.GetString("AD_Delete_cshtml_Execute_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Details {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Edit_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Edit_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Edit_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Edit_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Create_New {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Delete {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Details {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Index {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string AD_LastUpdated {
            get {
                return ResourceManager.GetString("AD_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Total number of {0} this month: &lt;span class=&quot;statistic&quot; id=&quot;{0}-total&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///      &lt;li&gt;Average number of {0} this month: &lt;span class=&quot;statistic&quot; id=&quot;{0}-average&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///      &lt;li&gt;Your best day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;
        ///      &lt;li&gt;Your worst day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;.
        /// </summary>
        public static string AD_MonthlySummaryStatistics {
            get {
                return ResourceManager.GetString("AD_MonthlySummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Data.
        /// </summary>
        public static string AD_Subtitle {
            get {
                return ResourceManager.GetString("AD_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string AD_Unit {
            get {
                return ResourceManager.GetString("AD_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Per Day.
        /// </summary>
        public static string AD_UnitsPerDaySummary {
            get {
                return ResourceManager.GetString("AD_UnitsPerDaySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Summary.
        /// </summary>
        public static string AD_UnitSummary {
            get {
                return ResourceManager.GetString("AD_UnitSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AD_Value {
            get {
                return ResourceManager.GetString("AD_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Total number of {0}: &lt;span class=&quot;statistic&quot; id=&quot;{0}-total&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///                    &lt;li&gt;Their best day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;
        ///                    &lt;li&gt;Their worst day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;.
        /// </summary>
        public static string AD_ViewUserStatistics {
            get {
                return ResourceManager.GetString("AD_ViewUserStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Total number of {0} this week: &lt;span class=&quot;statistic&quot; id=&quot;{0}-total&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///      &lt;li&gt;Average number of {0} this week: &lt;span class=&quot;statistic&quot; id=&quot;{0}-average&quot;&gt;&lt;/span&gt;&lt;/li&gt;
        ///      &lt;li&gt;Your best day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-max-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;
        ///      &lt;li&gt;Your worst day was &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-date&quot;&gt;&lt;/span&gt; with &lt;span class=&quot;statistic&quot; id=&quot;{0}-min-value&quot;&gt;&lt;/span&gt; {0}.&lt;/li&gt;.
        /// </summary>
        public static string AD_WeeklySummaryStatistics {
            get {
                return ResourceManager.GetString("AD_WeeklySummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Create_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Delete_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Details_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Edit_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        public static string AdminCommunitiesController_Index_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Control Panel.
        /// </summary>
        public static string AdminControlPanelTitle {
            get {
                return ResourceManager.GetString("AdminControlPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string AdminTeamsController_Index_Title {
            get {
                return ResourceManager.GetString("AdminTeamsController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string AdminTeamsController_Subtitle {
            get {
                return ResourceManager.GetString("AdminTeamsController_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time Summary.
        /// </summary>
        public static string AllTimeSummary {
            get {
                return ResourceManager.GetString("AllTimeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Accounts.
        /// </summary>
        public static string ApplicationUsersController_Index_Title {
            get {
                return ResourceManager.GetString("ApplicationUsersController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ApplicationUsersController_Teamname {
            get {
                return ResourceManager.GetString("ApplicationUsersController_Teamname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} records.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string Audit_IpAddress {
            get {
                return ResourceManager.GetString("Audit_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Parameters.
        /// </summary>
        public static string Audit_RequestParams {
            get {
                return ResourceManager.GetString("Audit_RequestParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Accessed.
        /// </summary>
        public static string Audit_UrlAccessed {
            get {
                return ResourceManager.GetString("Audit_UrlAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type.
        /// </summary>
        public static string challenge_categoryUnitId {
            get {
                return ResourceManager.GetString("challenge_categoryUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        public static string challenge_communityChallenges {
            get {
                return ResourceManager.GetString("challenge_communityChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string challenge_complete {
            get {
                return ResourceManager.GetString("challenge_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string challenge_endTime {
            get {
                return ResourceManager.GetString("challenge_endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string challenge_groupchallenges {
            get {
                return ResourceManager.GetString("challenge_groupchallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string challenge_startTime {
            get {
                return ResourceManager.GetString("challenge_startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community challenges.
        /// </summary>
        public static string Challenges_communityChallenges {
            get {
                return ResourceManager.GetString("Challenges_communityChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Challenges.
        /// </summary>
        public static string Challenges_completedChallenges {
            get {
                return ResourceManager.GetString("Challenges_completedChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Challenges.
        /// </summary>
        public static string Challenges_completedcomChallenges {
            get {
                return ResourceManager.GetString("Challenges_completedcomChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Challenges.
        /// </summary>
        public static string Challenges_completedgroupChallenges {
            get {
                return ResourceManager.GetString("Challenges_completedgroupChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group challenges .
        /// </summary>
        public static string Challenges_groupChallenges {
            get {
                return ResourceManager.GetString("Challenges_groupChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges not entered.
        /// </summary>
        public static string Challenges_notEntered {
            get {
                return ResourceManager.GetString("Challenges_notEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges you have entered.
        /// </summary>
        public static string Challenges_youAreSignedUpTo {
            get {
                return ResourceManager.GetString("Challenges_youAreSignedUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language!.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URL.
        /// </summary>
        public static string community_endpointUrl {
            get {
                return ResourceManager.GetString("community_endpointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string community_name {
            get {
                return ResourceManager.GetString("community_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data removed.
        /// </summary>
        public static string dataRemovalAudit_dataRemoved {
            get {
                return ResourceManager.GetString("dataRemovalAudit_dataRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date removed.
        /// </summary>
        public static string dataRemovalAudit_date {
            get {
                return ResourceManager.GetString("dataRemovalAudit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string dataRemovalAudit_message {
            get {
                return ResourceManager.GetString("dataRemovalAudit_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete your account?.
        /// </summary>
        public static string Delete_User_Prompt {
            get {
                return ResourceManager.GetString("Delete_User_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete my account..
        /// </summary>
        public static string Delete_User_Prompt_Button {
            get {
                return ResourceManager.GetString("Delete_User_Prompt_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that your data will be NON-RECOVERABLE if you proceed..
        /// </summary>
        public static string Delete_User_Prompt_Warning {
            get {
                return ResourceManager.GetString("Delete_User_Prompt_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Your Account.
        /// </summary>
        public static string Delete_User_Title {
            get {
                return ResourceManager.GetString("Delete_User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myemail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_cshtml_Execute_Error {
            get {
                return ResourceManager.GetString("Error_cshtml_Execute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeController_About_About {
            get {
                return ResourceManager.GetString("HomeController_About_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string HomeController_About_application_description {
            get {
                return ResourceManager.GetString("HomeController_About_application_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string HomeController_Contact_contact_page_header {
            get {
                return ResourceManager.GetString("HomeController_Contact_contact_page_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string HomeController_Contact_title {
            get {
                return ResourceManager.GetString("HomeController_Contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeController_Index_Home_Page {
            get {
                return ResourceManager.GetString("HomeController_Index_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string identityModel_dob {
            get {
                return ResourceManager.GetString("identityModel_dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string identityModel_nickname {
            get {
                return ResourceManager.GetString("identityModel_nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string identityModel_Team {
            get {
                return ResourceManager.GetString("identityModel_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Name.
        /// </summary>
        public static string job_id {
            get {
                return ResourceManager.GetString("job_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string job_Minutes {
            get {
                return ResourceManager.GetString("job_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Type.
        /// </summary>
        public static string job_schedtype {
            get {
                return ResourceManager.GetString("job_schedtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        public static string job_tasktype {
            get {
                return ResourceManager.GetString("job_tasktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Members.
        /// </summary>
        public static string Leader_NumMembers {
            get {
                return ResourceManager.GetString("Leader_NumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Leader Board.
        /// </summary>
        public static string LeaderBoards_GroupLeaderBoardTitle {
            get {
                return ResourceManager.GetString("LeaderBoards_GroupLeaderBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Leader Boards.
        /// </summary>
        public static string LeaderBoards_IndexGroupTitle {
            get {
                return ResourceManager.GetString("LeaderBoards_IndexGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Leader Boards.
        /// </summary>
        public static string LeaderBoards_IndexParticipantTitle {
            get {
                return ResourceManager.GetString("LeaderBoards_IndexParticipantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Board.
        /// </summary>
        public static string LeaderBoards_LeaderBoardTitle {
            get {
                return ResourceManager.GetString("LeaderBoards_LeaderBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Leader Board.
        /// </summary>
        public static string LeaderBoards_ParticipantLeaderBoardTitle {
            get {
                return ResourceManager.GetString("LeaderBoards_ParticipantLeaderBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string Lockout_cshtml_Execute_Locked_Out {
            get {
                return ResourceManager.GetString("Lockout_cshtml_Execute_Locked_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPhoneNumber.
        /// </summary>
        public static string Manage_AddPhoneNumber_cshtml_Execute_AddPhoneNumber {
            get {
                return ResourceManager.GetString("Manage_AddPhoneNumber_cshtml_Execute_AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Manage_AddPhoneNumber_cshtml_Execute_Phone_Number {
            get {
                return ResourceManager.GetString("Manage_AddPhoneNumber_cshtml_Execute_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Manage_ChangePassword_cshtml_Execute_Change_Password {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_cshtml_Execute_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Change_password {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Manage {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_ManageLogins_cshtml_Execute_Manage_external_logins {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_cshtml_Execute_Manage_external_logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string Manage_SetPassword_cshtml_Execute_Create_Password {
            get {
                return ResourceManager.GetString("Manage_SetPassword_cshtml_Execute_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string Manage_VerifyPhoneNumber_cshtml_Execute_Verify_Phone_Number {
            get {
                return ResourceManager.GetString("Manage_VerifyPhoneNumber_cshtml_Execute_Verify_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Activity Data.
        /// </summary>
        public static string ManageActivityData {
            get {
                return ResourceManager.GetString("ManageActivityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Communities.
        /// </summary>
        public static string ManageCommunities {
            get {
                return ResourceManager.GetString("ManageCommunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: .
        /// </summary>
        public static string ManageController_AddPhoneNumber_security_code_is {
            get {
                return ResourceManager.GetString("ManageController_AddPhoneNumber_security_code_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account Details.
        /// </summary>
        public static string ManageController_EditAccount_Manage {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_DateOfBirth {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_EmailAddress {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_Nickname {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_Team {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ManageController_Index_error {
            get {
                return ResourceManager.GetString("ManageController_Index_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Details.
        /// </summary>
        public static string ManageController_Index_Manage {
            get {
                return ResourceManager.GetString("ManageController_Index_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ManageController_Index_password_changed {
            get {
                return ResourceManager.GetString("ManageController_Index_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string ManageController_Index_password_set {
            get {
                return ResourceManager.GetString("ManageController_Index_password_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string ManageController_Index_phone_number_added {
            get {
                return ResourceManager.GetString("ManageController_Index_phone_number_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string ManageController_Index_two_factor_authentication_provider_set {
            get {
                return ResourceManager.GetString("ManageController_Index_two_factor_authentication_provider_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string ManageController_ManageLogins_external_login_removed {
            get {
                return ResourceManager.GetString("ManageController_ManageLogins_external_login_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string ManageController_phone_number_removed {
            get {
                return ResourceManager.GetString("ManageController_phone_number_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string ManageController_VerifyPhoneNumber_Failed_verify_phone {
            get {
                return ResourceManager.GetString("ManageController_VerifyPhoneNumber_Failed_verify_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Teams.
        /// </summary>
        public static string ManageTeams {
            get {
                return ResourceManager.GetString("ManageTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Summary.
        /// </summary>
        public static string MonthlySummary {
            get {
                return ResourceManager.GetString("MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BeatsThis Month.
        /// </summary>
        public static string MonthlySummaryTitle_TotalBeats {
            get {
                return ResourceManager.GetString("MonthlySummaryTitle_TotalBeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Steps This Month.
        /// </summary>
        public static string MonthlySummaryTitle_TotalSteps {
            get {
                return ResourceManager.GetString("MonthlySummaryTitle_TotalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type.
        /// </summary>
        public static string result_categoryUnit {
            get {
                return ResourceManager.GetString("result_categoryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Roles_Create_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("Roles_Create_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Roles.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_List_Roles {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_List_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Create_New_Role {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Create_New_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Index {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Create_New_Role {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Create_New_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageUserRoles.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_ManageUserRoles {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_ManageUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Select {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully !.
        /// </summary>
        public static string RolesController_Create_Role_created_successfully {
            get {
                return ResourceManager.GetString("RolesController_Create_Role_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role removed from this user successfully !.
        /// </summary>
        public static string RolesController_DeleteRoleForUser_Role_removed_from_user_successfully {
            get {
                return ResourceManager.GetString("RolesController_DeleteRoleForUser_Role_removed_from_user_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t belong to selected role..
        /// </summary>
        public static string RolesController_DeleteRoleForUser_user_doesnt_belong_role {
            get {
                return ResourceManager.GetString("RolesController_DeleteRoleForUser_user_doesnt_belong_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        public static string RoleType_Label {
            get {
                return ResourceManager.GetString("RoleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Community.
        /// </summary>
        public static string team_communityId {
            get {
                return ResourceManager.GetString("team_communityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string team_name {
            get {
                return ResourceManager.GetString("team_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string UserDelete_Title {
            get {
                return ResourceManager.GetString("UserDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string UserDetails_Title {
            get {
                return ResourceManager.GetString("UserDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account Details.
        /// </summary>
        public static string UserEdit_Title {
            get {
                return ResourceManager.GetString("UserEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View User.
        /// </summary>
        public static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Summary.
        /// </summary>
        public static string WeeklySummary {
            get {
                return ResourceManager.GetString("WeeklySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Beats This Week.
        /// </summary>
        public static string WeeklySummaryTitle_TotalBeats {
            get {
                return ResourceManager.GetString("WeeklySummaryTitle_TotalBeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Steps This Week.
        /// </summary>
        public static string WeeklySummaryTitle_TotalSteps {
            get {
                return ResourceManager.GetString("WeeklySummaryTitle_TotalSteps", resourceCulture);
            }
        }
    }
}
