//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _Layout_cshtml_Execute_About {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Data.
        /// </summary>
        public static string _Layout_cshtml_Execute_ActivityData {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_ActivityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string _Layout_cshtml_Execute_Admin {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string _Layout_cshtml_Execute_Application_name {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Application_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string _Layout_cshtml_Execute_Contact {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FitBit.
        /// </summary>
        public static string _Layout_cshtml_Execute_FitBit {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_FitBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _Layout_cshtml_Execute_Home {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string _Layout_cshtml_Execute_Jobs {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Log_in {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Register {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string AccountController_Login_Invalid_login_attempt {
            get {
                return ResourceManager.GetString("AccountController_Login_Invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string AccountController_VerifyCode_Invalid_code {
            get {
                return ResourceManager.GetString("AccountController_VerifyCode_Invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Create_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Create_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AD_Create_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("AD_Create_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Delete_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Delete_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AD_Delete_cshtml_Execute_Delete {
            get {
                return ResourceManager.GetString("AD_Delete_cshtml_Execute_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Details {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Details_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Details_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string AD_Edit_cshtml_Execute_Back_to_List {
            get {
                return ResourceManager.GetString("AD_Edit_cshtml_Execute_Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Edit_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Edit_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Create_New {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Delete {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Details {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string AD_Index_cshtml_Execute_Index {
            get {
                return ResourceManager.GetString("AD_Index_cshtml_Execute_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Data.
        /// </summary>
        public static string AD_Subtitle {
            get {
                return ResourceManager.GetString("AD_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Create_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Delete_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Details_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string AdminCommunitiesController_Edit_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        public static string AdminCommunitiesController_Index_Title {
            get {
                return ResourceManager.GetString("AdminCommunitiesController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Control Panel.
        /// </summary>
        public static string AdminControlPanelTitle {
            get {
                return ResourceManager.GetString("AdminControlPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string AdminTeamsController_Index_Title {
            get {
                return ResourceManager.GetString("AdminTeamsController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string AdminTeamsController_Subtitle {
            get {
                return ResourceManager.GetString("AdminTeamsController_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ApplicationUsersController_Index_Title {
            get {
                return ResourceManager.GetString("ApplicationUsersController_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ApplicationUsersController_Teamname {
            get {
                return ResourceManager.GetString("ApplicationUsersController_Teamname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language!.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myemail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_cshtml_Execute_Error {
            get {
                return ResourceManager.GetString("Error_cshtml_Execute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeController_About_About {
            get {
                return ResourceManager.GetString("HomeController_About_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string HomeController_About_application_description {
            get {
                return ResourceManager.GetString("HomeController_About_application_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string HomeController_Contact_contact_page_header {
            get {
                return ResourceManager.GetString("HomeController_Contact_contact_page_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string HomeController_Contact_title {
            get {
                return ResourceManager.GetString("HomeController_Contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeController_Index_Home_Page {
            get {
                return ResourceManager.GetString("HomeController_Index_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string Lockout_cshtml_Execute_Locked_Out {
            get {
                return ResourceManager.GetString("Lockout_cshtml_Execute_Locked_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPhoneNumber.
        /// </summary>
        public static string Manage_AddPhoneNumber_cshtml_Execute_AddPhoneNumber {
            get {
                return ResourceManager.GetString("Manage_AddPhoneNumber_cshtml_Execute_AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Manage_AddPhoneNumber_cshtml_Execute_Phone_Number {
            get {
                return ResourceManager.GetString("Manage_AddPhoneNumber_cshtml_Execute_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Manage_ChangePassword_cshtml_Execute_Change_Password {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_cshtml_Execute_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Change_password {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage_Index_cshtml_Execute_Manage {
            get {
                return ResourceManager.GetString("Manage_Index_cshtml_Execute_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_ManageLogins_cshtml_Execute_Manage_external_logins {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_cshtml_Execute_Manage_external_logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string Manage_SetPassword_cshtml_Execute_Create_Password {
            get {
                return ResourceManager.GetString("Manage_SetPassword_cshtml_Execute_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string Manage_VerifyPhoneNumber_cshtml_Execute_Verify_Phone_Number {
            get {
                return ResourceManager.GetString("Manage_VerifyPhoneNumber_cshtml_Execute_Verify_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Activity Data.
        /// </summary>
        public static string ManageActivityData {
            get {
                return ResourceManager.GetString("ManageActivityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Communities.
        /// </summary>
        public static string ManageCommunities {
            get {
                return ResourceManager.GetString("ManageCommunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: .
        /// </summary>
        public static string ManageController_AddPhoneNumber_security_code_is {
            get {
                return ResourceManager.GetString("ManageController_AddPhoneNumber_security_code_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account Details.
        /// </summary>
        public static string ManageController_EditAccount_Manage {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_DateOfBirth {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_EmailAddress {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_Nickname {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ManageController_EditAccount_ManageController_EditAccount_Team {
            get {
                return ResourceManager.GetString("ManageController_EditAccount_ManageController_EditAccount_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ManageController_Index_error {
            get {
                return ResourceManager.GetString("ManageController_Index_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Details.
        /// </summary>
        public static string ManageController_Index_Manage {
            get {
                return ResourceManager.GetString("ManageController_Index_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ManageController_Index_password_changed {
            get {
                return ResourceManager.GetString("ManageController_Index_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string ManageController_Index_password_set {
            get {
                return ResourceManager.GetString("ManageController_Index_password_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string ManageController_Index_phone_number_added {
            get {
                return ResourceManager.GetString("ManageController_Index_phone_number_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string ManageController_Index_two_factor_authentication_provider_set {
            get {
                return ResourceManager.GetString("ManageController_Index_two_factor_authentication_provider_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string ManageController_ManageLogins_external_login_removed {
            get {
                return ResourceManager.GetString("ManageController_ManageLogins_external_login_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string ManageController_phone_number_removed {
            get {
                return ResourceManager.GetString("ManageController_phone_number_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string ManageController_VerifyPhoneNumber_Failed_verify_phone {
            get {
                return ResourceManager.GetString("ManageController_VerifyPhoneNumber_Failed_verify_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Teams.
        /// </summary>
        public static string ManageTeams {
            get {
                return ResourceManager.GetString("ManageTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Roles_Create_cshtml_Execute_Create {
            get {
                return ResourceManager.GetString("Roles_Create_cshtml_Execute_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Roles.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_List_Roles {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_List_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_Edit_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_Edit_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Create_New_Role {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Create_New_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Index {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_Index_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_Index_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Create_New_Role {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Create_New_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Role.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Manage_User_Role {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Manage_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageUserRoles.
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_ManageUserRoles {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_ManageUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        public static string Roles_ManageUserRoles_cshtml_Execute_Select {
            get {
                return ResourceManager.GetString("Roles_ManageUserRoles_cshtml_Execute_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully !.
        /// </summary>
        public static string RolesController_Create_Role_created_successfully {
            get {
                return ResourceManager.GetString("RolesController_Create_Role_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role removed from this user successfully !.
        /// </summary>
        public static string RolesController_DeleteRoleForUser_Role_removed_from_user_successfully {
            get {
                return ResourceManager.GetString("RolesController_DeleteRoleForUser_Role_removed_from_user_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t belong to selected role..
        /// </summary>
        public static string RolesController_DeleteRoleForUser_user_doesnt_belong_role {
            get {
                return ResourceManager.GetString("RolesController_DeleteRoleForUser_user_doesnt_belong_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
