//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace GoAber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public class ActivityData
    {
        public ActivityData() { }

        public ActivityData(int categoryUnitID, string applicationUserID, DateTime date, DateTime now, int steps)
        {
            this.categoryUnitId = categoryUnitID;
            this.ApplicationUserId = applicationUserID;
            this.date = date;
            this.lastUpdated = now;
            this.value = steps;
        }

        public int Id { get; set; }
        public int categoryUnitId { get; set; }
        
        [DisplayName("Value")]
        public Nullable<int> value { get; set; }

        [DisplayName("Last Updated")]
        public Nullable<System.DateTime> lastUpdated { get; set; }

        [DisplayName("Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> date { get; set; }

        public virtual CategoryUnit categoryunit { get; set; }

        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}
