//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data.Entity;

    public class ActivityData
    {
        public ActivityData()
        {
            
        }

        public ActivityData(int categoryUnitID, int userID, DateTime date, DateTime now, int steps)
        {
            categoryUnitId = categoryUnitID;
            userId = userID;
            this.date = date;
            this.lastUpdated = now;
            this.value = steps;
        }

        public int Id { get; set; }
        public int categoryUnitId { get; set; }
        public int userId { get; set; }

        [DisplayName("Value")]
        public Nullable<int> value { get; set; }
        [DisplayName("Last Updated")]
        public Nullable<System.DateTime> lastUpdated { get; set; }
        [DisplayName("Date")]
        public Nullable<System.DateTime> date { get; set; }
        public virtual CategoryUnit categoryunit { get; set; }
        public virtual User user { get; set; }

        //public class MovieDBContext : DbContext
        //{
        //    public DbSet<ActivityData> ActivityData { get; set; }
        //}
    }
}
