//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryUnit()
        {
            this.activitydatas = new HashSet<ActivityData>();
        }
    
        public int Id { get; set; }
        public int categoryId { get; set; }
        public int unitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityData> activitydatas { get; set; }
        public virtual Category category { get; set; }
        public virtual Unit unit { get; set; }
    }
}
