//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.userchallenges = new HashSet<UserChallenge>();
            this.groupchallenges = new HashSet<GroupChallenge>();
            this.communityChallenges = new HashSet<CommunityChallenge>();
        }
    
        public string Id { get; set; }
        [DisplayName("Activity type")]
        public int categoryUnitId { get; set; }
        [DisplayName("Activity type")]
        public virtual CategoryUnit categoryUnit { get; set; }


        [Display(Name = "Challenge_StartTime", ResourceType = typeof(Resources.Resources))]
        public System.DateTime startTime { get; set; }
        [Display(Name = "Challenge_EndTime", ResourceType = typeof(Resources.Resources))]
        public Nullable<System.DateTime> endTime { get; set; }
        [Display(Name = "Challenge_Name", ResourceType = typeof(Resources.Resources))]
        public string name { get; set; }
        // public Nullable<int> communityStartedBy { get; set; }

        [Display(Name = "Challenge_Complete", ResourceType = typeof(Resources.Resources))]
        public bool complete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChallenge> userchallenges { get; set; }
        [Display(Name = "Challenge_Groups", ResourceType = typeof(Resources.Resources))]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupChallenge> groupchallenges { get; set; }
        [Display(Name = "Challenge_Communities", ResourceType = typeof(Resources.Resources))]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityChallenge> communityChallenges { get; set; }

    }
}
