//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Device
    {
        public int Id { get; set; }
        public int deviceTypeId { get; set; }

        [MaxLength(450)]
        public string accessToken { get; set; }
        [MaxLength(450)]
        public string refreshToken { get; set; }
        public Nullable<System.DateTime> tokenExpiration { get; set; }
    
        public virtual DeviceType deviceType { get; set; }

        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser user { get; set; }

        internal void ConstructionFactory(string accessToken, string refreshToken, int id, DateTime? accessTokenExpirationUtc, string v)
        {
            this.accessToken = accessToken;
            this.refreshToken = refreshToken;
            this.deviceTypeId = id;
            this.tokenExpiration = accessTokenExpirationUtc;
            this.ApplicationUserId = v;
        }
    }
}
