//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber.RemoteChallengeWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChallengeData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChallengeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        private int categoryUnitIdField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int communityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int categoryUnitId {
            get {
                return this.categoryUnitIdField;
            }
            set {
                if ((this.categoryUnitIdField.Equals(value) != true)) {
                    this.categoryUnitIdField = value;
                    this.RaisePropertyChanged("categoryUnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int communityId {
            get {
                return this.communityIdField;
            }
            set {
                if ((this.communityIdField.Equals(value) != true)) {
                    this.communityIdField = value;
                    this.RaisePropertyChanged("communityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int categoryUnitIdField;
        
        private int valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string challengeIdField;
        
        private int communityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int categoryUnitId {
            get {
                return this.categoryUnitIdField;
            }
            set {
                if ((this.categoryUnitIdField.Equals(value) != true)) {
                    this.categoryUnitIdField = value;
                    this.RaisePropertyChanged("categoryUnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string challengeId {
            get {
                return this.challengeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.challengeIdField, value) != true)) {
                    this.challengeIdField = value;
                    this.RaisePropertyChanged("challengeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int communityId {
            get {
                return this.communityIdField;
            }
            set {
                if ((this.communityIdField.Equals(value) != true)) {
                    this.communityIdField = value;
                    this.RaisePropertyChanged("communityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteChallengeWS.GoAberChallengesWSSoap")]
    public interface GoAberChallengesWSSoap {
        
        // CODEGEN: Generating message contract since element name challenge from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecieveChallenge", ReplyAction="*")]
        GoAber.RemoteChallengeWS.RecieveChallengeResponse RecieveChallenge(GoAber.RemoteChallengeWS.RecieveChallengeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecieveChallenge", ReplyAction="*")]
        System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveChallengeResponse> RecieveChallengeAsync(GoAber.RemoteChallengeWS.RecieveChallengeRequest request);
        
        // CODEGEN: Generating message contract since element name result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecieveResult", ReplyAction="*")]
        GoAber.RemoteChallengeWS.RecieveResultResponse RecieveResult(GoAber.RemoteChallengeWS.RecieveResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecieveResult", ReplyAction="*")]
        System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveResultResponse> RecieveResultAsync(GoAber.RemoteChallengeWS.RecieveResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveChallengeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecieveChallenge", Namespace="http://tempuri.org/", Order=0)]
        public GoAber.RemoteChallengeWS.RecieveChallengeRequestBody Body;
        
        public RecieveChallengeRequest() {
        }
        
        public RecieveChallengeRequest(GoAber.RemoteChallengeWS.RecieveChallengeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecieveChallengeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GoAber.RemoteChallengeWS.ChallengeData challenge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userGroup;
        
        public RecieveChallengeRequestBody() {
        }
        
        public RecieveChallengeRequestBody(GoAber.RemoteChallengeWS.ChallengeData challenge, int userGroup) {
            this.challenge = challenge;
            this.userGroup = userGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveChallengeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecieveChallengeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoAber.RemoteChallengeWS.RecieveChallengeResponseBody Body;
        
        public RecieveChallengeResponse() {
        }
        
        public RecieveChallengeResponse(GoAber.RemoteChallengeWS.RecieveChallengeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecieveChallengeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RecieveChallengeResult;
        
        public RecieveChallengeResponseBody() {
        }
        
        public RecieveChallengeResponseBody(bool RecieveChallengeResult) {
            this.RecieveChallengeResult = RecieveChallengeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecieveResult", Namespace="http://tempuri.org/", Order=0)]
        public GoAber.RemoteChallengeWS.RecieveResultRequestBody Body;
        
        public RecieveResultRequest() {
        }
        
        public RecieveResultRequest(GoAber.RemoteChallengeWS.RecieveResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecieveResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GoAber.RemoteChallengeWS.ResultData result;
        
        public RecieveResultRequestBody() {
        }
        
        public RecieveResultRequestBody(GoAber.RemoteChallengeWS.ResultData result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecieveResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoAber.RemoteChallengeWS.RecieveResultResponseBody Body;
        
        public RecieveResultResponse() {
        }
        
        public RecieveResultResponse(GoAber.RemoteChallengeWS.RecieveResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecieveResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GoAber.RemoteChallengeWS.ResultData RecieveResultResult;
        
        public RecieveResultResponseBody() {
        }
        
        public RecieveResultResponseBody(GoAber.RemoteChallengeWS.ResultData RecieveResultResult) {
            this.RecieveResultResult = RecieveResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GoAberChallengesWSSoapChannel : GoAber.RemoteChallengeWS.GoAberChallengesWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoAberChallengesWSSoapClient : System.ServiceModel.ClientBase<GoAber.RemoteChallengeWS.GoAberChallengesWSSoap>, GoAber.RemoteChallengeWS.GoAberChallengesWSSoap {
        
        public GoAberChallengesWSSoapClient() {
        }
        
        public GoAberChallengesWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoAberChallengesWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoAberChallengesWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoAberChallengesWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoAber.RemoteChallengeWS.RecieveChallengeResponse GoAber.RemoteChallengeWS.GoAberChallengesWSSoap.RecieveChallenge(GoAber.RemoteChallengeWS.RecieveChallengeRequest request) {
            return base.Channel.RecieveChallenge(request);
        }
        
        public bool RecieveChallenge(GoAber.RemoteChallengeWS.ChallengeData challenge, int userGroup) {
            GoAber.RemoteChallengeWS.RecieveChallengeRequest inValue = new GoAber.RemoteChallengeWS.RecieveChallengeRequest();
            inValue.Body = new GoAber.RemoteChallengeWS.RecieveChallengeRequestBody();
            inValue.Body.challenge = challenge;
            inValue.Body.userGroup = userGroup;
            GoAber.RemoteChallengeWS.RecieveChallengeResponse retVal = ((GoAber.RemoteChallengeWS.GoAberChallengesWSSoap)(this)).RecieveChallenge(inValue);
            return retVal.Body.RecieveChallengeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveChallengeResponse> GoAber.RemoteChallengeWS.GoAberChallengesWSSoap.RecieveChallengeAsync(GoAber.RemoteChallengeWS.RecieveChallengeRequest request) {
            return base.Channel.RecieveChallengeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveChallengeResponse> RecieveChallengeAsync(GoAber.RemoteChallengeWS.ChallengeData challenge, int userGroup) {
            GoAber.RemoteChallengeWS.RecieveChallengeRequest inValue = new GoAber.RemoteChallengeWS.RecieveChallengeRequest();
            inValue.Body = new GoAber.RemoteChallengeWS.RecieveChallengeRequestBody();
            inValue.Body.challenge = challenge;
            inValue.Body.userGroup = userGroup;
            return ((GoAber.RemoteChallengeWS.GoAberChallengesWSSoap)(this)).RecieveChallengeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoAber.RemoteChallengeWS.RecieveResultResponse GoAber.RemoteChallengeWS.GoAberChallengesWSSoap.RecieveResult(GoAber.RemoteChallengeWS.RecieveResultRequest request) {
            return base.Channel.RecieveResult(request);
        }
        
        public GoAber.RemoteChallengeWS.ResultData RecieveResult(GoAber.RemoteChallengeWS.ResultData result) {
            GoAber.RemoteChallengeWS.RecieveResultRequest inValue = new GoAber.RemoteChallengeWS.RecieveResultRequest();
            inValue.Body = new GoAber.RemoteChallengeWS.RecieveResultRequestBody();
            inValue.Body.result = result;
            GoAber.RemoteChallengeWS.RecieveResultResponse retVal = ((GoAber.RemoteChallengeWS.GoAberChallengesWSSoap)(this)).RecieveResult(inValue);
            return retVal.Body.RecieveResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveResultResponse> GoAber.RemoteChallengeWS.GoAberChallengesWSSoap.RecieveResultAsync(GoAber.RemoteChallengeWS.RecieveResultRequest request) {
            return base.Channel.RecieveResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoAber.RemoteChallengeWS.RecieveResultResponse> RecieveResultAsync(GoAber.RemoteChallengeWS.ResultData result) {
            GoAber.RemoteChallengeWS.RecieveResultRequest inValue = new GoAber.RemoteChallengeWS.RecieveResultRequest();
            inValue.Body = new GoAber.RemoteChallengeWS.RecieveResultRequestBody();
            inValue.Body.result = result;
            return ((GoAber.RemoteChallengeWS.GoAberChallengesWSSoap)(this)).RecieveResultAsync(inValue);
        }
    }
}
