//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devicetype
    {
        public int idDeviceType { get; set; }
        public string name { get; set; }
        public string tokenEndpoint { get; set; }
        public string consumerKey { get; set; }
        public string consumerSecret { get; set; }
        public string clientId { get; set; }
        public string authorizationEndpoint { get; set; }
    }
}
