//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoAberEntities : DbContext
    {
        public GoAberEntities()
            : base("name=GoAberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityData> ActivityDatas { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryUnit> CategoryUnits { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Devicetype> Devicetypes { get; set; }
        public virtual DbSet<GroupChallenge> GroupChallenges { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserChallenge> UserChallenges { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
