//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoAberEntities : DbContext
    {
        public GoAberEntities()
            : base("name=GoAberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityData> ActivityDatas1 { get; set; }
        public virtual DbSet<Category> Categories1 { get; set; }
        public virtual DbSet<CategoryUnit> CategoryUnits1 { get; set; }
        public virtual DbSet<Challenge> Challenges1 { get; set; }
        public virtual DbSet<Community> Communities1 { get; set; }
        public virtual DbSet<Device> Devices1 { get; set; }
        public virtual DbSet<Devicetype> Devicetypes1 { get; set; }
        public virtual DbSet<Group> Groups1 { get; set; }
        public virtual DbSet<GroupChallenge> GroupChallenges1 { get; set; }
        public virtual DbSet<Unit> Units1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<UserChallenge> UserChallenges { get; set; }
        public virtual DbSet<UserCredential> UserCredentials2 { get; set; }
        public virtual DbSet<UserRole> UserRoles1 { get; set; }
    }
}
