//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class goaberEntities : DbContext
    {
        public goaberEntities()
            : base("name=goaberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activitydata> activitydatas { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<categoryunit> categoryunits { get; set; }
        public virtual DbSet<challenge> challenges { get; set; }
        public virtual DbSet<community> communities { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<devicetype> devicetypes { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<groupchallenge> groupchallenges { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userchallenge> userchallenges { get; set; }
        public virtual DbSet<usercredential> usercredentials { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
    }
}
