//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAber
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.activitydatas = new HashSet<activitydata>();
            this.userchallenges = new HashSet<userchallenge>();
        }
    
        public int idUser { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
        public int userRoleId { get; set; }
        public Nullable<int> userCredentialsId { get; set; }
        public Nullable<int> groupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activitydata> activitydatas { get; set; }
        public virtual group group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userchallenge> userchallenges { get; set; }
        public virtual usercredential usercredential { get; set; }
        public virtual userrole userrole { get; set; }
    }
}
